### ISSUE TITLE
Getting Google API

### ISSUE THREAD

**Issue by saeid85** [danialkalbasi/react-native-power-translator#8]
Hi,
I want to use the Power Translator in my app, but the problem is, while I want to get an API key, although it is free, Google Cloud ask me to create a Billing Account and add my Credit Card!!
Is there any way I can have a test API key & if I decide to use it in production version then I setup Billing Account!?

Thanks

**Comment by danialkalbasi** [comment]
Hi @saeid85, you need to add your credit card information in order to use the service. If it's your first time that you are using Google services, most probably you will have some free quote. Also, don't worry about the charge. Make sure to just enable the service you need (in this case Translation) and it will be a very small charge for few API calls. 

Here you can check the pricing: https://cloud.google.com/translate/pricing

**Comment by saeid85** [comment]
Thank you so much @danialkalbasi. So there is no way to use Google Translate without adding Credit Card... If there is no way then I will add a card!

**Comment by danialkalbasi** [comment]
@saeid85 Thanks and great to hear that you figure out the google service! I close this issue.
